config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :photos, only: [:index, :new, :create, :edit, :update, :destroy] do
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :access, :rails_admin # grant access to rails_admin
      can :manage, :all # allow superadmins to do anything
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  has_many :photos

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name:     auth.extra.raw_info.name,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url:   auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name:     auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name)

  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    if params[:back]
      @photo = Photo.new(photo_params)
    else
      @photo = Photo.new
    end
  end

  def confirm
    @photo = Photo.new(photo_params)
    render :new if @photo.invalid?
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to photos_path, notice: "新規投稿しました"
      NoticeMailer.sendmail_photo(@photo).deliver
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @photo.update(photo_params)
    redirect_to photos_path, notice: "更新しました"
  end

  def destroy
    @photo.destroy
    redirect_to photos_path, notice: "削除しました"
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :content, :image)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  # def choose_new_or_edit
  #   if action_name == 'new' || action_name == 'confirm'
  #     confirm_photos_path
  #   elsif action_name = 'edit'
  #     photo_path
  #   end
  # end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoshare</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="<%= asset_path "photoshare_icon.png" %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <!-- <ul>
    <li><%= link_to image_tag("photoshare_home.png", class: "home-image", alt: "home"), root_path %></li>
    <li><%= link_to "写真一覧", photos_path %></li>
    <li><%= link_to "新規投稿", new_photo_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "マイページ", edit_user_registration_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <li><%= link_to "サインアップ", new_user_registration_path %></li>
    <% end %>
  </ul> -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("photoshare_home.png", class: "home-image", alt: "home"), root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "写真一覧", photos_path %></li>
          <li><%= link_to "新規投稿", new_photo_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "マイページ", edit_user_registration_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "サインアップ", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

<%= yield %>

<footer>
  <p>運営会社DIVE INTO CODE株式会社</p>
  <p>© 2015-2017 Copyright DIVE INTO CODE Corp.</p>
</footer>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h3><%= @photo.errors.count %>件のエラーがあります。</h3>

      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
        <li class="error-message"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :写真 %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <br>
  <%= f.label :本文 %>
  <%= f.text_area :content, class: 'form-control', rows: 5 %>
  <br>
  <%= f.submit "投稿", class: 'btn btn-default btn-block' %>
<% end %>

<p><br><%= link_to "写真一覧へ", photos_path %></p>

app/views/photos/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>

    <%= form_for(@photo) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :image_cache %>

      <p>タイトル:<%= @photo.title %></p>
      <p>写真:<%= @photo.image %></p>
      <p>本文:<%= @photo.content %></p>
      <%= f.submit "登録する", class: 'btn btn-default btn-block' %>
    <% end %>

    <%= form_for(@photo, url: new_photo_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :image_cache %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>編集する</h2>
    <%= render 'form' %>
  </div>

</div>

app/views/photos/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
    <p><br /><%= notice %></p>
    <h1>写真一覧</h1>
    <p><%= link_to "新規投稿", new_photo_path, class: 'btn btn-default' %></p>
    <% @photos.reverse_each do |photo| %>
      <div class="row">
        <p>
          <span class="user-image"><%= profile_img(photo.user) %></span>
          <%= photo.user.name %>が投稿
        </p>
        <h4><strong><%= photo.title %></strong></h4>
        <% if photo.image? %>
          <br>
          <%= image_tag(photo.image) %>
          <br><br>
        <% end %>
        <p><%= photo.content %></p>
        <%= link_to "編集", edit_photo_path(photo.id), class: 'btn btn-default btn-sm' %>
        <%= link_to "削除", photo_path(photo.id), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-default btn-sm' %>
        <p><br><%= photo.updated_at.strftime("%F %R UTC") %><p>
      </div>
    <% end %>
    <div id="page-top-btn" class="page-top-btn">
      <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>新規投稿</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<section class="about">
  <p><%= notice %><%= alert %></p>
  <%= image_tag "photoshare.png", alt: "photoshare" %>
  <p>Photoshareは写真共有アプリです。</p>
  <p>
    <%= link_to image_tag("photoshare_camera.png", class: "camera-image", alt: "camera"), photos_path %>
  </p>
</section>